GET http://localhost:3001/api/persons HTTP/1.1

#### 
GET http://localhost:3001/api/persons/5 HTTP/1.1

###
DELETE http://localhost:3001/api/persons/6326bc05079e498061845f4e

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "mystery",
    "number": "041-000001"
}


###

GET http://localhost:3001/api/persons/6326bc05079e498061845f4e HTTP/1.1

###
GET http://localhost:3001/api/persons/info HTTP/1.1